# # to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1.5.1
# workflows:
#   build:
#     jobs:
#       # "cypress" is the name of the imported orb
#       # "run" is the name of the job defined in Cypress orb
#       - cypress/run

version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/cypress-cucumber-preprocessor
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: link the package
          command: |
            npm link
            npm link cypress-cucumber-preprocessor
      - run:
          name: run tests
          command: npm test
      - run:
          name: release
          command: npm run semantic-release || true
